### ISSUE TITLE
Error opening serial port: SYS_IOCTL: inappropriate ioctl for device

### ISSUE THREAD

**Issue by bseishen** [jacobsa/go-serial#45]
Trying to get this working in Windows Subsystem for Linux. "SYS_IOCTL: inappropriate ioctl for device" when trying to open the port.

**Comment by AlexxIT** [comment]
You need compile this little cpp app. And check output. Then change constants in code:
https://github.com/jacobsa/go-serial/blob/15cf729a72d49e837fa047a4142fa6e4d5ab45a1/serial/open_linux.go#L14-L25

Same problem on mips https://github.com/jacobsa/go-serial/issues/27

But @philipgreat fix was very helpful.
